# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Breelabs"
tagline: "Your Partner in Starting and Growing Your Business"
description: "Discover Breelabs, a premier consultancy dedicated to helping entrepreneurs take the first step in starting and growing their business. Learn about our mission, values, and the experienced team that provides personalized guidance and innovative strategies to ensure your business's success."
author: "Jon Brown"
logo: "/images/bree-logo.png"
locale: "en_US"
url: "https://breelabs.com/"
production:          true
email: jon@breelabs.com
description: Focused on helping aspiring entrepreneurs take their first step
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://breelabs.com" # the base hostname & protocol for your site, e.g. http://example.com
mailchimp-list: //breelabs.us21.list-manage.com/subscribe/post?u=c334574c74c4f57096a0cf9be&amp;id=5e4d95a16a&amp;f_id=0022f0e6f0
facebook:
 app_id: 112614115061936
 publisher: https://www.facebook.com/breelabs
 admins: https://www.facebook.com/breelabs
social:
  name: Jon Brown
  links:
    - https://www.facebook.com/breelabs
    - https://www.youtube.com/@breelabs
    - https://github.com/breelabs
    - https://www.linkedin.com/company/breelabs/
twitter:
  card: summary_large_image
webmaster_verifications:
  google: WrKoghT8yLHNso7CG7f6xsiV0ZlFGoL9SkIXX55Ia2g
#  bing: 
paginate: 4
paginate_path: /blog/page/:num
permalink: /blog/:categories/:year/:month/:day/:title.html

site_url:           http://localhost:4000
base_href:          http://localhost:4000
site_cdn:           http://localhost:4000

#site_url:           https://breelabs.com
#base_href:          https://breelabs.com
#site_cdn:           https://breelabs.com

feed:
  path: atom.xml
  
compress_images:
  images_path: "images/**/*.{gif,png,jpg,jpeg,svg}"
  
imageoptim:
  # Disabling svgo because it throws some error
  pngout: true
  svgo: false
  jpegrecompress:
    allow_lossy: true
    quality: 2
    max_quality: 80 
  
#twitter_username: jekyllrb
github_username:  jonbrown21

# Build settings
theme: null
# repository: breelabs/breelabs.io.git

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-compress-images

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
